pipeline {
    environment {
        registry = "https://docker.mjamsek.com"
        registryCredential = "nexus-username"
        dockerImageTag = "docker.mjamsek.com/echoer"
        dockerImage = ""

        COMMIT_AUTHOR = ""
        COMMIT_MESSAGE = ""
        PROJECT_VERSION = ""
        COMMIT_URL = ""
        DOCKER_IMAGE_VERSION = ""
    }

    agent any

    tools {
        nodejs "node-14"
    }

    stages {
        stage("Setting environment") {
            steps {
                script {
                    packageJson =readJSON file:"package.json"
                    PROJECT_VERSION = packageJson.version
                    COMMIT_MESSAGE = sh script: "git show -s --pretty='%s'", returnStdout: true
                    COMMIT_MESSAGE = COMMIT_MESSAGE.trim()
                    COMMIT_AUTHOR = sh script: "git show -s --pretty='%cn <%ce>'", returnStdout: true
                    COMMIT_AUTHOR = COMMIT_AUTHOR.trim()
                    COMMIT_URL = GIT_URL + "/commit/" + GIT_COMMIT
                    DOCKER_IMAGE_VERSION = "${PROJECT_VERSION}.${env.BUILD_NUMBER}"
                }
            }
        }
        stage("Building docker image") {
            steps {
                script {
                    dockerImage = docker.build dockerImageTag
                }
            }
        }
        stage("Publishing docker image") {
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        dockerImage.push(DOCKER_IMAGE_VERSION)
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage("Cleanup docker images") {
            steps {
                sh "docker rmi $dockerImageTag:${DOCKER_IMAGE_VERSION}"
                sh "docker rmi $dockerImageTag:latest"
            }
        }
    }
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME}' [<${env.BUILD_URL}|${env.BUILD_NUMBER}>]:\n'<${COMMIT_URL}|${COMMIT_MESSAGE}>' _from ${COMMIT_AUTHOR}_")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME}' [<${env.BUILD_URL}|${env.BUILD_NUMBER}>]:\n'<${COMMIT_URL}|${COMMIT_MESSAGE}>' _from ${COMMIT_AUTHOR}_")
        }
    }
}
